### ISSUE TITLE
Cannot find type 'BindableType' in scope

### ISSUE THREAD

**Issue by lexuanquynh** [tgdong2296/SimpleDemoCleanArchitecture#2]

**Comment by VuCuongHD96** [comment]
here you are:
https://github.com/VuCuongHD96/CookbookOne/blob/master/CookBook/Domain/Models/BindableType.swift

**Comment by tgdong2296** [comment]
@lexuanquynh 
I fixed this issue, please check new version in `main` branch.
Pull request: https://github.com/tgdong2296/SimpleDemoCleanArchitecture/pull/3
